targets:
  $default:
    sources:     
      - swaggers/**
      - lib/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/model/api/swagger/"
          output_folder: "lib/model/api/generated/"
          separate_models: true
          include_if_null: false